version: "3.6"
services:
  # MongoDB
  db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # API
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://db:27017/books
      REDIS_URI: redis://redis:6379
    links:
      - redis
      - db
    depends_on:
      - redis
      - db

volumes:
  mongodb-data:
